apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: az3xf8f2m-python 
  janus-idp.io/tekton: az3xf8f2m-python
  backstage.io/kubernetes-id: az3xf8f2m-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: az3xf8f2m-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml